### ISSUE TITLE
Crucial error! (No actual "supersymmetric" tensor is in your code)

### ISSUE THREAD

**Issue by JordanMicahBennett** [scijs/tensor-decomposition#1]
According to [this paper on arXiv](https://arxiv.org/pdf/0802.1681.pdf), the paper [you refer to](http://epubs.siam.org/doi/10.1137/S0895479801387413) in your [Readme file](https://github.com/scijs/tensor-decomposition/blob/master/README.md), doesn't actually deal with supersymmetric tensors.

Example lines from [the arXiv paper](https://arxiv.org/pdf/0802.1681.pdf) in question:

1. "Many authors have persistently mislabeled the latter a ‘supersymmetric tensor’ (cf. [10, [34](http://epubs.siam.org/doi/10.1137/S0895479801387413), 45])". 
    * The author mentions that your source material, reference  [34](http://epubs.siam.org/doi/10.1137/S0895479801387413), with title "[On the Best Rank-1 Approximation of Higher-Order Supersymmetric Tensors](http://epubs.siam.org/doi/10.1137/S0895479801387413)", wrongly labels its tensors as being supersymmetric!

2. "Such arrays have been improperly labeled ‘supersymmetric’ tensors (cf. [10, [34](http://epubs.siam.org/doi/10.1137/S0895479801387413), 45] among others)"
    * Once more, the author mentions that your source material, reference  [34](http://epubs.siam.org/doi/10.1137/S0895479801387413), with title "[On the Best Rank-1 Approximation of Higher-Order Supersymmetric Tensors](http://epubs.siam.org/doi/10.1137/S0895479801387413)", wrongly labels its tensors as being supersymmetric!

&nbsp;

Please read the urgent points below:
====

* I actually stumbled upon this error, because I was searching for someway to describe what I call a "[Supersymmetric Artificial Neural Network](https://github.com/JordanMicahBennett/Supersymmetric-artificial-neural-network)", but I couldn't find any actual [supersymmetric](https://en.wikipedia.org/wiki/Supersymmetry) relation in your code, which was labelled to contain "supersymmetric tensors"!!!!

* That I failed to find any actual [supersymmetric](https://en.wikipedia.org/wiki/Supersymmetry) thing in your code is no surprise, because your code, and the source material constitutes as you already probably know, [Symmetric tensors](https://en.wikipedia.org/wiki/Symmetric_tensor), rather than [actual supersymmetric tensors](https://arxiv.org/pdf/0903.0509.pdf) in string theory!!!

* [The actual supersymmetric tensor paper I revealed to you above](https://arxiv.org/pdf/0903.0509.pdf) doesn't describe any neural network, but it is legitimately string theory based, ***in contrast*** to the [source material](http://epubs.siam.org/doi/10.1137/S0895479801387413) your [Readme file](https://github.com/scijs/tensor-decomposition/blob/master/README.md) stipulates!!

**Comment by jaspervdg** [comment]
Hi, always nice to hear someone is interested in higher order tensors. As to the nomenclature used, it unfortunately varies, and, if I recall correctly, some people use "supersymmetric" to indicate that the tensors are invariant to all permutations of indices, reserving "symmetric" for tensors that are invariant to some permutations (but not others). I don't doubt that there are other uses of the word supersymmetric, and quite possibly these are even more common and/or better chosen. Annoying, but unfortunately a fact of scientific life.

However, it is not quite clear to me what the issue is, since we actually don't use the word "supersymmetric", sticking to "symmetric tensors", which they clearly are. The only thing referring to "supersymmetric" seems to be the citation, which we are clearly not going to change.
